trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Infrastructure_Provisioning
  displayName: "Provision ACR, Resource group on Azure"
  jobs:
    - job: Provision
      displayName: Validate and provision
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: $(azure-connection)
          backendAzureRmResourceGroupName: $(storage-resource-group)
          backendAzureRmStorageAccountName: $(storage-account)
          backendAzureRmContainerName: $(storage-container)
          backendAzureRmKey: $(storage-key)
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: $(azure-connection)
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: '--auto-approve'
          environmentServiceNameAzureRM: $(azure-connection)

    - job: Set_Pipeline_Variables
      steps:
      - task: PowerShell@2
        displayName: 'Capture Terraform output variables and push to pipeline variables'
        inputs:
          targetType: 'inline'
          script: |
            $tfoutput = (terraform output --json) | ConvertFrom-Json
            if ($tfoutput -eq $null) {
              Write-Host("No Terraform output variables found")
            } else {
              foreach($outputVar in $tfoutput.psobject.properties) { 
                Write-Host("##vso[task.setvariable variable=$($outputVar.name);]$($outputVar.value.value)")
                Write-Host("$($outputVar.name)-$($outputVar.value.value)")
              }
            }

- stage: Build_And_Deploy
  displayName: Build Docker image and publish stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: ubuntu-latest
    dependsOn: Infrastructure_Provisioning
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      displayName: Build and publish image to Azure Container Registry
      inputs:
        command: buildAndPush
        containerRegistry: $(ACR_LOGIN_SERVER)
        repository: "python-image"
        dockerfile: "**/Dockerfile"

# steps:
# - task: TerraformInstaller@1
#   inputs:
#     terraformVersion: 'latest'
# - task: TerraformTaskV4@4
#   inputs:
#     provider: 'azurerm'
#     command: 'init'
#     backendServiceArm: $(azure-connection)
#     backendAzureRmResourceGroupName: $(storage-resource-group)
#     backendAzureRmStorageAccountName: $(storage-account)
#     backendAzureRmContainerName: $(storage-container)
#     backendAzureRmKey: $(storage-key)
# - task: TerraformTaskV4@4
#   inputs:
#     provider: 'azurerm'
#     command: 'plan'
#     environmentServiceNameAzureRM: $(azure-connection)
# - task: TerraformTaskV4@4
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     commandOptions: '--auto-approve'
#     environmentServiceNameAzureRM: $(azure-connection)



