trigger:
- master

pool:
  vmImage: ubuntu-latest

# variables:
#   ARM_CLIENT_ID: $(APP_ID)
#   ARM_CLIENT_SECRET: $(CLIENT_SECRET)
#   ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
#   ARM_TENANT_ID: $(TENANT_ID)

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'logixos-azure-connection'
    backendAzureRmResourceGroupName: 'terraformStorage'
    backendAzureRmStorageAccountName: 'logixosterraform'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'logixos-azure-connection'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'logixos-azure-connection'

